apiVersion: batch/v1
kind: Job
metadata:
  name: job-hook-postinstall
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      containers:
        - name: post-install
          image: busybox
          imagePullPolicy: IfNotPresent

          command: ["sh", "-c", "echo post-install Pod is Running ; sleep 10"]

      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0

  backoffLimit: 3
  completions: 1
  parallelism: 1
