---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-monitor
  labels:
    app: test-monitor
spec:
  selector:
    matchLabels:
      app: test-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: test-monitor
    spec:
      restartPolicy: Always
      serviceAccountName: test  # 配置服务账号
      containers:
      - name:  test-monitor
        image:   test-in-cluster:v1
        command:
          - "./app"
        env:
        - name: "NAMESPACE"
          value: "default"
        - name: "TARGET_SVC_NAME"
          value: "nginx"
        - name: "TARGET_STS_MASTER_NAME"
          value: "nginx-master"
        - name: "TARGET_STS_BACKUP_NAME"
          value: "nginx-backup"
        - name: "TARGET_STS_CLIENT_NAME"
          value: "worker"
        - name: "MASTER_NODE_LABEL"
          value: "{\"app-master\":\"true\"}"
        - name: "BACKUP_NODE_LABEL"
          value: "{\"app-backup\":\"true\"}"
        - name: "MASTER_SVC_SELECTOR"
          value: "{\"app\": \"nginx-master\"}"
        - name: "BACKUP_SVC_SELECTOR"
          value: "{\"app\":\"nginx-backup\"}"
        - name: "LEASE_LOCK_NAME"
          value: "test"
        - name: "LEASE_MODE"
          value: "false"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app-master
                operator: In
                values:
                - "true"
            - matchExpressions:
              - key: app-backup
                operator: In
                values:
                - "true"