apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-master
spec:
  selector:
    matchLabels:
      app: nginx-master
  serviceName: nginx-master
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-master
    spec:
      terminationGracePeriodSeconds:  90
      containers:
      - name: nginx-master
        image: docker.io/library/nginx:1.16
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: master-data
      nodeSelector:
        app-master: "true"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-backup
spec:
  selector:
    matchLabels:
      app: nginx-backup
  serviceName: nginx-backup
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-backup
    spec:
      terminationGracePeriodSeconds:  90
      containers:
      - name: nginx-backup
        image: docker.io/library/nginx:1.16
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: backup-data
      nodeSelector:
        app-backup: "true"

---

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-master
# spec:
#   selector:
#     matchLabels:
#       app: nginx-master
#   template:
#     metadata:
#       labels:
#         app: nginx-master
#     spec:
#       containers:
#       - name: nginx-master
#         image: docker.io/library/nginx:1.16
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80
#       nodeSelector:
#         app-master: "true"
# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-backup
# spec:
#   selector:
#     matchLabels:
#       app: nginx-backup
#   template:
#     metadata:
#       labels:
#         app: nginx-backup
#     spec:
#       containers:
#       - name: nginx-backup
#         image: docker.io/library/nginx:1.16
#         resources:
#           limits:
#             memory: "128Mi"
#             cpu: "500m"
#         ports:
#         - containerPort: 80
#       nodeSelector:
#         app-backup: "true"