apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-data
spec:
  resources:
    requests:
      storage: 100M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-data
spec:
  resources:
    requests:
      storage: 100M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
