---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-monitor
rules:
- apiGroups: ["", "extensions", "apps", "coordination.k8s.io"]
  resources: ["services", "statefulsets", "pods", "leases"]
  verbs: ["get", "list", "patch", "watch", "update", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-example
  namespace: default
subjects:
# - kind: User
#   name: user-example
#   apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: test
  namespace: default
roleRef:
  kind: Role
  name: role-monitor
  apiGroup: rbac.authorization.k8s.io
