version: '3'

services:
  mysql-svc:
    container_name: mysql-svc
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql-data:/var/lib/mysql
